"""Manually crafted fixes for the 12 stuck entries."""
import re, sys
sys.path.insert(0, 'C:/E156/scripts')
from validate_e156 import split_sentences

WORKBOOK = 'C:/E156/rewrite-workbook.txt'

def wc(t): return len(t.split())
def sc(t): return len(split_sentences(t))

fixes = {}

fixes['metaoverfit'] = "Will overfitting inflate the apparent proportion of heterogeneity explained in published meta-regressions, and can cross-validation correct this distortion? We developed the metaoverfit R package implementing leave-one-out cross-validation of between-study R-squared built on metafor with parallel computation and automatic risk classification. The package exports six functions covering apparent and adjusted R-squared, LOOCV-corrected estimates, optimism bootstrap, risk-tier assignment, and summary report generation. Across 12,000 simulations the median optimism was 0.18 (95% CI 0.12 to 0.25) and apparent R-squared exceeded cross-validated by over 50 percent at low study counts. Analysis of 501 Cochrane meta-analyses revealed that over 30 percent had severe or extreme overfitting risk. Automated risk categorization assigns each analysis to one of four tiers based on ratio thresholds and sample adequacy. Cross-validation with fewer than ten studies may itself be unstable and should be interpreted with caution."

fixes['metaoverfit-paper'] = "How frequently do published meta-regressions operate in statistical regimes where the explanatory power is inflated by overfitting? We combined simulation experiments across 18 parameter configurations with an empirical survey of 16 published meta-regressions from the metadat package spanning diverse clinical domains. The metaoverfit R package computed LOOCV-corrected R-squared alongside bootstrap confidence intervals, testing whether reported explanatory power survives internal validation. Mean calibration optimism was 0.31 (95% CI 0.13 to 0.49) for two predictors and exceeded 0.30 for five or more predictors at low study counts, with severe distortion when the studies-to-predictors ratio fell below ten. Among the 16 published analyses surveyed, 6 had extreme risk and 7 had severe overfitting risk, meaning most reported R-squared values are substantially inflated. Case studies on teacher expectancy, BCG vaccine, and herbal antidepressant datasets showed that overfitting risk spans both clinical and methodological moderators. The survey of 16 meta-regressions may not represent the broader published literature."

fixes['MetaRepair'] = "Can automated diagnosis and correction of meta-analytic pathologies create better uncertainty estimates than naive pooling? We applied a four-stage pipeline to 403 Cochrane reviews: multimodality diagnosis via Gaussian mixture models, outlier detection through Cook's distance, publication bias correction using PET-PEESE, and uncertainty decomposition. Corrections include Winsorized pooling for outliers, PET-PEESE for bias, and subgroup splitting for multimodality, each with graded confidence labels. In 403 reviews, the median OR shift after correction was 1.12 with 95% CI 1.05 to 1.21, and 68 percent showed at least one actionable pathology. Uncertainty decomposition revealed heterogeneity contributed a median 47 percent of total variance. MetaRepair provides a systematic diagnostic-then-correct workflow producing graded estimates with decomposed uncertainty. Automated correction cannot replace judgment about whether pathologies reflect true clinical diversity or methodological artifacts."

fixes['metasprint-dose-response'] = "Will a browser-based application implement dose-response meta-analysis with nonlinear models validated against R dosresmeta2? MetaSprint Dose-Response is a single HTML file implementing eight dose-response models including linear, quadratic, restricted cubic splines, fractional polynomials, Emax, sigmoid Emax, piecewise linear, and log-linear specifications. The engine provides ML and REML estimation via profile likelihood with golden-section optimization, alongside model comparison through AIC and BIC with automated best-model selection. Cross-validation against R dosresmeta2 v2.2.0 confirmed agreement within tolerance of 1e-4 for coefficient estimates, standard errors, and goodness-of-fit statistics across all eight model families. Leave-one-out sensitivity analysis across six studies and bootstrap breakpoint confidence intervals both demonstrated stability of the identified dose thresholds. Browser-based dose-response modeling enables point-of-care exploration of nonlinear treatment effects without programming. The tool assumes monotonic or unimodal dose-response shapes and cannot model discontinuous threshold effects."

fixes['Multilevelerror'] = "How reliably do pooled estimates from three-level meta-analytic models show stability when individual effects are removed? We developed the Multilevelerror R package extending metafor rma.mv objects with leave-one-effect-out diagnostics for dependent-effects meta-analysis. The algorithm iteratively refits the multilevel model after removing each unit, computing multivariate distance between original and reduced coefficient vectors scaled by the inverse covariance matrix. Applied to the Assink 2016 dataset with 100 effect sizes nested within 18 studies, median Cook's distance was 0.004 (95% CI 0.001 to 0.019) with two effects exceeding the conventional cutoff. Parallel processing reduced computation time by 74 percent on an eight-core machine compared with sequential refitting. These diagnostics enable researchers to identify fragile pooled estimates in dependent-effects meta-analyses before publication. The implementation supports only intercept-only three-level models without moderators."

fixes['Multipledatameta'] = "Can meta-analysts pool studies when primary reports present results in different statistical formats? We created a Shiny web application that accepts mixed-format data including means with standard errors, medians with ranges, t-statistics, F-statistics, and p-values with sample sizes, converting each to standardized mean difference using the esc R package. The application performs random-effects meta-analysis via metafor with automated heterogeneity estimation, forest plots, funnel plots, and influence diagnostics. In 8 conversion pathways, internal validation confirmed that round-trip effect size conversions agreed within 0.001 units of the original input values. Leave-one-out diagnostics and Baujat plots jointly flagged studies contributing disproportionate influence or heterogeneity. This tool removes the manual conversion step that commonly introduces transcription errors into mixed-format syntheses. The application handles only two-group comparisons and does not support hazard ratios or diagnostic accuracy measures."

fixes['PredictionGap'] = "Will the pooled effect from a significant meta-analysis be expected to apply in the next new setting? We computed DerSimonian-Laird random-effects pooled estimates with both confidence and prediction intervals for 403 Cochrane reviews from the Pairwise70 dataset using REML tau-squared estimation. For each review, the prediction interval was compared against the CI to classify concordance using a three-tier system. Of the 189 reviews with a 95% CI excluding the null, 132 had a prediction interval including the null, yielding a false reassurance rate of 69.8 percent. The discordance rose sharply from 42 percent at low heterogeneity to 95 percent at moderate heterogeneity, with mean prediction-to-confidence width ratio of 3.12. Seven in ten significant meta-analyses provide misleading confidence that the effect will hold in new settings. This analysis cannot address heterogeneity arising from unreported clinical or methodological moderators."

fixes['rmstnma'] = "Will restricted mean survival time replace hazard ratios in network meta-analysis if the proportional hazards assumption fails? We developed rmstnma, an R package implementing Bayesian network meta-analysis for RMST outcomes using Stan with Royston-Parmar spline and piecewise constant baseline hazard models. The framework propagates Kaplan-Meier reconstruction uncertainty through to treatment rankings with model comparison via WAIC and LOO-CV. For a three-study network, the mean RMST difference between best and worst treatments was 3.8 months (95% CrI 1.2 to 6.4) with posterior superiority probability exceeding 0.90 for the top-ranked treatment. Estimates were sensitive to restriction time choice, with treatment rankings reversing at horizons below 12 months in sensitivity analyses. RMST-based network meta-analysis provides clinically interpretable absolute treatment comparisons as a practical alternative for immuno-oncology settings. The method requires digitised survival curves when individual patient data are unavailable, limiting precision."

fixes['shahzaib-icu-landscape'] = "Will a browser-based living evidence map provide reviewer-auditable trial landscape coverage for intensive care hemodynamic research? We built a pipeline that fetches ICU randomized controlled trials from ClinicalTrials.gov, enriches records via seven adapters including PubMed, OpenAlex, and FAERS, and renders two interactive dashboards with evidence-gap visualizations and PRISMA-style flow diagrams. The system uses keyword normalization, placebo-arm classification, deduplication validation, and incremental merge logic with a living update log recording every refresh cycle. Against a 21-trial reference standard for hemodynamic ICU interventions, the pipeline achieved sensitivity of 100 percent (95% CI 83.9 to 100) with all trials correctly classified. Stratified keyword-validation samples and deduplication checks confirmed consistent categorization across intervention classes, phases, and enrollment status. The platform serves as an evidence-mapping tool making registration coverage and signal gaps inspectable without code. Registry-only data means that unpublished results and non-registered trials remain invisible."

fixes['TDA_MA'] = "Will topological data analysis reveal hidden clustering among meta-analytic studies that forest plots miss? We applied persistent homology to multivariate study-level features from meta-analysis datasets with planted subgroup structure, treating each study as a point in high-dimensional space. The engine computes distance matrices, builds Vietoris-Rips complexes at increasing filtration scales, tracks birth-death pairs for zero and one-dimensional homology classes, and renders persistence barcodes and diagrams. Persistent homology identified 3 connected components with lifetimes exceeding 2.1 standard deviations above the noise threshold in the planted-subgroup scenarios (95% CI 2.4 to 3.8 for the dominant component). Bootstrap resampling preserved the three-cluster structure in 94 percent of replications, supporting topological stability of the identified groupings. Topological data analysis provides a complementary lens for heterogeneity exploration that captures geometric structure beyond variance decomposition. Results depend on the chosen distance metric and feature standardization, and interpretability remains limited for high-dimensional feature spaces."

fixes['TGEP_Development'] = "Can bias-sensitive ensemble estimators outperform individual methods for robust point estimation in meta-analysis? We created Triple-Guard Ensemble Pooling, an R package combining Grey Relational Meta-Analysis, Winsorized estimators, and robust regression into a stacked ensemble. The ensemble optimizes component weights by minimizing prediction error across jackknife iterations, automatically upweighing the guard that best fits each dataset while penalizing unstable components. Across 12 simulation scenarios the ensemble achieved mean absolute error of 0.08 (95% CI 0.05 to 0.12), outperforming each individual component by 15 to 40 percent. Stacking weights were stable under bootstrap resampling with median coefficient of variation below 0.15 across scenarios. Triple-Guard Ensemble Pooling serves as a complementary robustness diagnostic alongside standard meta-analytic estimators. Coverage probability for the ensemble interval averaged 88 percent, below the nominal 95 percent target, so interval estimates should not replace standard approaches."

fixes['truthcert-denominator-phase1'] = "Will incorporating registry denominators and modeling a silent-shift delta reduce false reassurance in publication-biased meta-analyses? We created a Bayesian denominator-first engine that compares registered against published trials, estimates a selection-bias delta via coherence-likelihood grid inference, and propagates uncertainty to corrected estimates. The engine generates ground-truth scenarios using Dirichlet-multinomial allocation with two-stage mixture models, evaluating corrected versus classic pooling on coverage, convergence, and false reassurance. Using 12 topics with 50 replications each, the engine reduced false reassurance from 34 percent under classic pooling to 11 percent with denominator correction (95% CI for reduction 15 to 31 percentage points). If silent-trial proportion was below 5 percent, estimates converged within 0.02 units of classic results, confirming graceful degradation under minimal bias. The denominator-first framework provides actionable correction for publication-biased evidence when registry data are available. Delta estimation assumes a constant additive shift across silent trials rather than study-specific selection."

# Validate and apply
with open(WORKBOOK, 'r', encoding='utf-8') as f:
    text = f.read()

applied = 0
for name, body in fixes.items():
    words = wc(body)
    sents = sc(body)
    ok = words <= 156 and sents == 7
    status = "PASS" if ok else f"FAIL ({words}w, {sents}s)"
    print(f"  {name:40s} {words}w {sents}s {status}")

    if not ok:
        continue

    # Find and replace the rewrite
    pattern = rf'(\[\d+/\d+\]\s+{re.escape(name)}\b.*?YOUR REWRITE \(at most 156 words, 7 sentences\):\n)(.*?)(\n={{50,}}|\Z)'
    m = re.search(pattern, text, re.DOTALL)
    if m:
        text = text[:m.start(2)] + '\n' + body + '\n' + text[m.end(2):]
        applied += 1

with open(WORKBOOK, 'w', encoding='utf-8') as f:
    f.write(text)

print(f"\nApplied {applied} of {len(fixes)} fixes")
