import re

e156_texts = {
    "41644273": "Do glucagon-like peptide-1 receptor agonists reduce cardiorenal events in patients with chronic kidney disease? This meta-analysis pooled nine randomized controlled trials enrolling 21,717 patients with CKD, the vast majority having coexisting type 2 diabetes. Random-effects models estimated pooled relative risks for kidney events, cardiovascular events, and mortality from databases searched through December 2024. GLP-1 receptor agonists reduced major adverse kidney events by 16% (RR 0.84, 95% CI 0.76-0.94), major adverse cardiovascular events by 16% (RR 0.84, 95% CI 0.72-0.97), and all-cause mortality by 17% (RR 0.83, 95% CI 0.76-0.90). Gastrointestinal adverse events were substantially elevated, with nausea risk increased fourfold (RR 4.14, 95% CI 2.70-6.33) and vomiting risk tripled (RR 3.05, 95% CI 1.88-4.97). GLP-1 receptor agonists confer consistent cardiorenal protection in CKD patients who predominantly have diabetes, with clinically meaningful reductions in both kidney and cardiovascular endpoints. These benefits must be weighed against frequent gastrointestinal side effects, and generalizability to non-diabetic CKD populations remains unestablished.",

    "41565576": "Does the cardiovascular benefit of GLP-1 receptor agonists differ across racial populations? Nine randomized placebo-controlled trials including 8,164 Asian, 4,036 Black or African American, and 62,503 White participants with type 2 diabetes or obesity were pooled through November 2025. Random-effects meta-analyses estimated hazard ratios for major adverse cardiovascular events and ratios of hazard ratios comparing treatment effects between populations. Asian participants showed the largest MACE reduction (HR 0.73, 95% CI 0.63-0.85), followed by White participants (HR 0.86, 95% CI 0.81-0.91), with the between-group difference reaching significance (ratio of HRs 0.84, 95% CI 0.71-0.98). Black or African American participants showed a nonsignificant trend toward benefit (HR 0.88, 95% CI 0.67-1.15), limited by smaller sample size. GLP-1 receptor agonists reduce cardiovascular events across populations, but Asian patients appear to derive significantly greater relative risk reduction than White patients. The Black or African American subgroup remains underpowered, highlighting the need for more diverse enrollment in future cardiovascular outcome trials.",

    "41884216": "Can cell-based therapies improve healing outcomes in diabetic foot ulcers beyond conventional wound care management? Thirty-two randomized controlled trials enrolling 2,059 patients with diabetic foot ulcers were pooled, assessing nine outcomes including ulcer healing and amputation rates. Random-effects meta-analysis with leave-one-out sensitivity analysis and subgroup analyses by cell type, dose, and route were performed in R. Cell therapy significantly improved ulcer healing (OR 4.64, 95% CI 3.11-6.90) and reduced amputation (OR 0.29, 95% CI 0.18-0.49), while shortening healing time by 16.8 days and alleviating rest pain. Subgroup analyses identified autologous bone marrow mesenchymal stem cells via intramuscular injection at medium-to-high doses as the optimal protocol, with patients having shorter diabetes duration and larger ulcers deriving greatest benefit. Cell therapy, particularly autologous bone marrow stem cells, substantially improves diabetic foot ulcer healing and limb salvage with consistent effects across multiple endpoints. Optimal dosing protocols and target populations require confirmation in adequately powered multicenter trials outside single-country settings.",

    "41679389": "Do eHealth interventions improve mental health and quality of life in older adults with subthreshold depression? Thirty-two randomized controlled trials including 3,973 participants with subthreshold depression were synthesized from five databases using random-effects meta-analysis. Subgroup analyses and meta-regressions identified factors moderating the intervention effects on depressive symptoms as the primary outcome. eHealth interventions produced small-to-moderate reductions in depressive symptoms (Hedges g=-0.35, 95% CI -0.45 to -0.24), moderate reductions in anxiety (g=-0.47, 95% CI -0.73 to -0.20), and small improvements in quality of life (g=0.21, 95% CI 0.08 to 0.34). Virtual reality-based interventions were the most effective eHealth component (g=-1.08, 95% CI -1.59 to -0.56), while greater improvements emerged in participants without comorbidities receiving shorter single-component interventions. eHealth approaches offer a scalable, accessible method for managing subthreshold depression in older adults, with virtual reality showing particularly strong effects. Long-term durability of benefits remains unconfirmed, and optimal delivery formats for diverse older populations need investigation through high-quality trials.",

    "41856154": "Are cannabinoids effective for treating mental health disorders and substance use disorders in adults? Fifty-four randomized controlled trials enrolling 2,477 participants were identified from five databases covering 1980 to 2025, with bias assessed using Cochrane RoB 2.0. Random-effects meta-analysis synthesized standardized mean differences and odds ratios, with evidence graded using GRADE. Cannabinoids reduced cannabis withdrawal symptoms (SMD -0.29, 95% CI -0.57 to -0.02), tic severity in Tourette syndrome (SMD -0.68, 95% CI -1.03 to -0.34), and autistic traits (SMD -0.36, 95% CI -0.66 to -0.07), while increasing sleep duration in insomnia. No significant effects emerged for anxiety, psychotic disorders, PTSD, anorexia nervosa, or opioid use disorder, and cannabinoids increased cocaine craving and any-cause adverse events (NNTH=7). Cannabinoids show narrow therapeutic value limited to cannabis use disorder, tics, insomnia, and autism symptoms, with generally low-quality supporting evidence. Routine clinical use for most mental disorders is currently unjustified given the scarcity and low certainty of available trial data.",

    "41720441": "Does flood exposure increase the risk of post-traumatic stress disorder, depression, and anxiety in affected populations? A systematic review identified 107 studies on flood-related mental health outcomes published between 2004 and 2024, with 18 providing sufficient data for random-effects meta-analysis. Pooled odds ratios were estimated from fully adjusted models, with subgroup analyses examining sociodemographic and contextual moderators. Flood exposure was associated with significantly elevated odds of PTSD (OR 3.01), depression (OR 2.38), and anxiety (OR 2.84), with key vulnerability factors including female gender, unemployment, pre-existing mental illness, repeated flood exposure, and severe housing damage. Longitudinal evidence indicated that mental health impacts frequently persist for years beyond the acute disaster period, with disproportionate effects on socially vulnerable populations. Flooding approximately triples the odds of PTSD and nearly triples anxiety risk, establishing it as a potent environmental determinant of mental illness. These findings are limited by observational designs, heterogeneous measurement instruments, and the inability to definitively establish causality.",

    "41672480": "What is the efficacy of immune checkpoint inhibitors in unselected metastatic castration-resistant prostate cancer without biomarker-based patient selection criteria? Individual patient data were reconstructed from published survival curves of 21 clinical trials enrolling 1,580 patients with metastatic castration-resistant prostate cancer treated with immune checkpoint inhibitors. Kaplan-Meier analysis estimated pooled survival rates, and subgroup comparisons evaluated monotherapy versus combination regimens across all trials. The pooled one-year and two-year overall survival rates were 63% and 39% respectively, while six-month and twelve-month progression-free survival rates were 41% and 17%. Combination therapy using checkpoint inhibitors plus another systemic agent showed significantly better overall and progression-free survival than mono or dual checkpoint inhibitor therapy alone (all comparisons p<0.05). Immune checkpoint inhibitors show modest but measurable activity in unselected metastatic castration-resistant prostate cancer, with combination regimens consistently outperforming monotherapy across survival endpoints. The absence of randomized comparisons against standard-of-care therapies and lack of biomarker stratification limit definitive conclusions about optimal patient selection.",

    "41290455": "Does adding immune checkpoint inhibitors to chemotherapy improve outcomes in triple-negative breast cancer across both treatment settings? Randomized controlled trials comparing immunotherapy plus chemotherapy with chemotherapy alone in triple-negative breast cancer were identified from PubMed, Embase, and Cochrane Library through June 2022. Hazard ratios and odds ratios were pooled using random-effects models for pathological complete response, event-free survival, progression-free survival, and adverse events. In the neoadjuvant setting, checkpoint inhibitors improved pathological complete response (OR 1.90, 95% CI 1.28-2.83) and event-free survival (HR 0.65, 95% CI 0.51-0.82), with benefits persisting regardless of PD-L1 status. In the adjuvant setting, checkpoint inhibitors prolonged progression-free survival in both the intention-to-treat population (HR 0.82, 95% CI 0.74-0.90) and PD-L1-positive subgroups (HR 0.71, 95% CI 0.62-0.82). Adding checkpoint inhibitors to chemotherapy consistently improves pathological and survival outcomes in triple-negative breast cancer irrespective of treatment timing. Increased rates of serious and immune-related adverse events including thyroid dysfunction necessitate careful toxicity monitoring throughout treatment.",

    "41827017": "Do adjuvant immune checkpoint inhibitors improve survival after curative resection or ablation for hepatocellular carcinoma? Eighteen studies enrolling 3,478 patients who received adjuvant checkpoint inhibitors after curative resection or ablation were pooled from multiple databases. The generic inverse-variance method with random-effects models estimated hazard ratios for recurrence-free and overall survival outcomes. Adjuvant checkpoint inhibitor-based therapy significantly improved recurrence-free survival (HR 0.51, 95% CI 0.44-0.60), with both monotherapy (HR 0.46, 95% CI 0.35-0.60) and combination regimens with tyrosine kinase inhibitors (HR 0.55, 95% CI 0.45-0.68) showing consistent benefit. Overall survival was also significantly improved (HR 0.51, 95% CI 0.40-0.65), with benefits maintained across subgroups defined by curative treatment modality and study design. Adjuvant checkpoint inhibitors approximately halve the risk of recurrence and death following curative hepatocellular carcinoma treatment, representing a potential paradigm shift in post-surgical management. These results derive predominantly from observational and geographically restricted studies, requiring confirmation through global randomized phase III trials with longer follow-up.",

    "41827802": "Do antibiotics administered near immune checkpoint inhibitor treatment impair immunotherapy efficacy across solid tumor types? Fifteen observational studies encompassing 52,489 patients treated with checkpoint inhibitors were identified from PubMed, Scopus, and EMBASE for publications between 2018 and 2025. Random-effects meta-analysis estimated pooled hazard ratios for overall survival and progression-free survival, with sensitivity analysis performed in non-small cell lung cancer. Antibiotic exposure was associated with significantly worse overall survival (HR 1.16, 95% CI 1.03-1.29) and a trend toward shorter progression-free survival (HR 1.11, 95% CI 0.95-1.27) compared with no antibiotic exposure. In the non-small cell lung cancer subgroup, antibiotics were consistently associated with inferior progression-free survival and, accounting for heterogeneity, significantly reduced overall survival. Antibiotics given near checkpoint inhibitor initiation are associated with clinically meaningful survival impairment across tumor types, consistent with microbiome-mediated disruption of antitumor immunity. The observational design precludes causal inference, and prospective studies integrating microbiome profiling are needed to define safe antibiotic stewardship strategies.",
}

all_pass = True
for pmid, text in e156_texts.items():
    words = text.strip().split()
    wc = len(words)
    # Count sentences by splitting on sentence-ending punctuation followed by space+capital
    sents = re.split(r'(?<=[.?!])\s+(?=[A-Z])', text.strip())
    status = "PASS" if wc == 156 else "FAIL"
    if wc != 156:
        all_pass = False
    print(f"PMID {pmid}: {wc} words, {len(sents)} sentences -- {status}")

print(f"\nAll 10 E156 micro-papers at exactly 156 words: {all_pass}")
