"""
Apply the 134 editorial rewrites generated by generate_rewrites.py
to entries that have a real CURRENT BODY but blank YOUR REWRITE.
"""

import re
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))
from generate_rewrites import rewrite_body, count_words, split_sentences


def main():
    workbook_path = 'C:/E156/rewrite-workbook.txt'

    with open(workbook_path, 'r', encoding='utf-8') as f:
        text = f.read()

    sections = re.split(r'(={50,})', text)

    applied = 0
    already_done = 0

    for i, sec in enumerate(sections):
        if re.match(r'={50,}', sec):
            continue

        m = re.search(r'\[(\d+)/302\]\s+(.+)', sec)
        if not m:
            continue

        num, name = int(m.group(1)), m.group(2).strip()

        # Check if already has rewrite
        rw_match = re.search(r'YOUR REWRITE[^\n]*:\s*\n(.*)', sec, re.DOTALL)
        has_rewrite = rw_match and len(rw_match.group(1).strip()) > 10

        if has_rewrite:
            already_done += 1
            continue

        # Check if has real body (not zero, not capsule)
        has_zero = 'CURRENT BODY (0 words)' in sec or '[No E156 body generated yet]' in sec
        if has_zero:
            continue

        # Extract current body
        body_match = re.search(r'CURRENT BODY[^\n]*:\s*\n(.+?)(?=YOUR REWRITE)', sec, re.DOTALL)
        if not body_match:
            continue

        body = body_match.group(1).strip()
        if len(body) < 50:
            continue

        # Generate rewrite
        title_match = re.search(r'TITLE:\s*(.+)', sec)
        title = title_match.group(1).strip() if title_match else name

        rewrite = rewrite_body(body, title)
        wc = count_words(rewrite)

        # Insert rewrite
        rw_header_match = re.search(r'(YOUR REWRITE[^\n]*:\s*\n)', sec)
        if rw_header_match:
            insert_pos = rw_header_match.end()
            sec = sec[:insert_pos] + '\n' + rewrite + '\n' + sec[insert_pos:]
            sections[i] = sec
            applied += 1

    # Write output
    output = ''.join(sections)
    with open(workbook_path, 'w', encoding='utf-8') as f:
        f.write(output)

    print(f'Editorial rewrites applied: {applied}')
    print(f'Already had rewrite: {already_done}')

    # Final count
    with open(workbook_path, 'r', encoding='utf-8') as f:
        final_text = f.read()

    final_sections = re.split(r'={50,}', final_text)
    filled = 0
    blank = 0
    for sec in final_sections:
        m2 = re.search(r'\[(\d+)/302\]', sec)
        if not m2:
            continue
        rw = re.search(r'YOUR REWRITE[^\n]*:\s*\n(.*)', sec, re.DOTALL)
        if rw and len(rw.group(1).strip()) > 10:
            filled += 1
        else:
            blank += 1

    print(f'\nFinal status: {filled} filled, {blank} blank out of {filled+blank} total')


if __name__ == '__main__':
    main()
