"""
generate_protocol.py — Generate E156-PROTOCOL.md in each project repo.

Creates a timestamped protocol file linking the project to its E156 entry.
Reads CURRENT BODY from the workbook and writes E156-PROTOCOL.md.

Usage:
    python generate_protocol.py              # Generate all missing protocols
    python generate_protocol.py --force      # Regenerate all (overwrite existing)
    python generate_protocol.py --dry-run    # Preview only
"""

import argparse
import re
import sys
import io
from datetime import datetime
from pathlib import Path

sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
sys.stderr = io.TextIOWrapper(sys.stderr.buffer, encoding='utf-8', errors='replace')

WORKBOOK = Path("C:/E156/rewrite-workbook.txt")
GH_USER = "mahmood726-cyber"


def parse_workbook_entries():
    """Parse rewrite-workbook.txt into structured entries."""
    content = WORKBOOK.read_text(encoding="utf-8")
    separator = "=" * 70
    blocks = content.split(separator)
    entries = []

    for block in blocks:
        block = block.strip()
        if not block:
            continue

        # Match entry header: [N/TOTAL] Name
        header_match = re.match(r'\[(\d+)/\d+\]\s+(.+)', block)
        if not header_match:
            continue

        entry_num = int(header_match.group(1))
        name = header_match.group(2).strip()

        # Extract fields
        title = ""
        entry_type = ""
        estimand = ""
        data = ""
        path = ""
        current_body = ""
        submitted = False

        for line in block.splitlines():
            line_s = line.strip()
            if line_s.startswith("TITLE:"):
                title = line_s[6:].strip()
            elif line_s.startswith("TYPE:"):
                parts = line_s[5:].split("|")
                entry_type = parts[0].strip()
                if len(parts) > 1 and "ESTIMAND:" in parts[1]:
                    estimand = parts[1].split("ESTIMAND:")[1].strip()
            elif line_s.startswith("DATA:"):
                data = line_s[5:].strip()
            elif line_s.startswith("PATH:"):
                path = line_s[5:].strip()
            elif line_s.startswith("SUBMITTED: [x]"):
                submitted = True

        # Extract CURRENT BODY
        body_match = re.search(
            r'CURRENT BODY \(\d+ words\):\n(.+?)(?:\nYOUR REWRITE|\Z)',
            block, re.DOTALL
        )
        if body_match:
            current_body = body_match.group(1).strip()

        if path:
            entries.append({
                "num": entry_num,
                "name": name,
                "title": title,
                "type": entry_type,
                "estimand": estimand,
                "data": data,
                "path": path,
                "current_body": current_body,
                "submitted": submitted,
            })

    return entries


def generate_protocol_md(entry):
    """Generate the E156-PROTOCOL.md content for an entry."""
    now = datetime.now().strftime("%Y-%m-%d")
    repo_name = Path(entry["path"]).name.lower().replace("_", "-").replace(" ", "-")
    pages_url = f"https://{GH_USER}.github.io/{repo_name}/"

    lines = [
        f"# E156 Protocol: {entry['title']}",
        "",
        f"**Project**: {entry['name']}",
        f"**E156 Entry**: #{entry['num']}",
        f"**Type**: {entry['type']}",
        f"**Primary Estimand**: {entry['estimand']}",
        f"**Data**: {entry['data']}",
        "",
        f"**Date Created**: {now}",
        f"**Date Last Updated**: {now}",
        f"**Status**: {'SUBMITTED' if entry['submitted'] else 'DRAFT'}",
        "",
        f"**Dashboard**: [{pages_url}]({pages_url})",
        "",
        "## E156 Abstract (CURRENT BODY)",
        "",
        entry["current_body"],
        "",
        "---",
        f"*Generated by E156 pipeline on {now}*",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Generate E156-PROTOCOL.md files")
    parser.add_argument("--force", action="store_true", help="Overwrite existing protocols")
    parser.add_argument("--dry-run", action="store_true", help="Preview only")
    args = parser.parse_args()

    entries = parse_workbook_entries()
    generated = 0
    skipped = 0
    missing_path = 0

    for entry in entries:
        proj_path = Path(entry["path"])
        if not proj_path.is_dir():
            missing_path += 1
            continue

        protocol_file = proj_path / "E156-PROTOCOL.md"

        if protocol_file.exists() and not args.force:
            # Update the "Date Last Updated" line if body changed
            existing = protocol_file.read_text(encoding="utf-8", errors="replace")
            if entry["current_body"] in existing:
                skipped += 1
                continue

        if entry["submitted"]:
            # Don't regenerate submitted protocols unless --force
            if protocol_file.exists() and not args.force:
                skipped += 1
                continue

        content = generate_protocol_md(entry)

        if args.dry_run:
            print(f"  DRY  {entry['name']:45s}  -> {protocol_file}")
        else:
            protocol_file.write_text(content, encoding="utf-8")
            print(f"  GEN  {entry['name']:45s}  -> E156-PROTOCOL.md")

        generated += 1

    print(f"\nGenerated: {generated}, Skipped: {skipped}, Missing path: {missing_path}")
    print(f"Total entries: {len(entries)}")


if __name__ == "__main__":
    main()
