#requires -Version 5
<#
.SYNOPSIS
  Install the E156 workbook commit-scope guard as a pre-commit hook.

.DESCRIPTION
  Per review-findings-session-2026-05-06.md P0-2 (Domain Expert + Red-Team):
  blocks commits that bundle a `[N/total]` denominator sweep with
  substantive `CURRENT BODY:` / `YOUR REWRITE:` / `TITLE:`/etc. changes
  in the same diff.

  Run once per fresh clone. Re-running is safe (overwrites the hook).
#>
$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$hookDir = Join-Path $repoRoot '.git\hooks'
$hookPath = Join-Path $hookDir 'pre-commit'

if (-not (Test-Path $hookDir)) { throw "missing .git/hooks — is this a git repo?" }

$hookContent = @'
#!/bin/sh
# Auto-generated by scripts/install_pre_commit.ps1
# See scripts/check_workbook_commit.py for the actual logic.
exec python "$(git rev-parse --show-toplevel)/scripts/check_workbook_commit.py"
'@

# Write with LF line endings (git hooks must be POSIX-style).
[System.IO.File]::WriteAllText($hookPath, $hookContent -replace "`r`n", "`n")
Write-Host "Installed pre-commit hook at $hookPath"
Write-Host "Test: stage a denominator sweep + body change in the same commit; should block."
Write-Host "Bypass: E156_BUNDLED_OK=1 git commit -m '...'"
